#!/bin/bash
# Generated by setup-agents — agent reminder on every prompt

agents_dir=".claude/agents"
[ -d "$agents_dir" ] || exit 0

echo "=== Agent Reminder ==="
echo "INSTRUCTION: Delegate to the right agent. Do not do the work directly."
echo ""

for f in "$agents_dir"/*.md; do
  [ -f "$f" ] || continue
  name=$(basename "$f" .md)
  desc=$(awk '/^description:/{sub(/^description: */, ""); print; exit}' "$f")
  printf "  @%-14s — %s\n" "$name" "$desc"
done

echo ""
echo "Workflow: @architect → @coder → @reviewer → @tester"
echo "Start with @architect for any feature, fix, or significant change."
echo "=== End Agent Reminder ==="
