#!/bin/bash
# Generated by setup-agents — branch-aware git context on session start

echo "=== Git Context (pre-fetched — do not re-run git log) ==="
echo "INSTRUCTION: This git context has already been fetched for you. Use it directly. Do not call git log, git status, or git diff to obtain information already present here."
echo ""

branch=$(git branch --show-current 2>/dev/null)
[ -z "$branch" ] && exit 0
echo "Branch: $branch"
echo ""

# Detect main branch name
main_branch="main"
git rev-parse --verify main >/dev/null 2>&1 || main_branch="master"

if [ "$branch" = "$main_branch" ]; then
  echo "Recent commits:"
  git log --oneline -5
else
  merge_base=$(git merge-base "$main_branch" HEAD 2>/dev/null)
  if [ -n "$merge_base" ]; then
    branch_commits=$(git log --oneline "$merge_base"..HEAD 2>/dev/null)
    if [ -n "$branch_commits" ]; then
      count=$(echo "$branch_commits" | wc -l | tr -d ' ')
      echo "Branch commits ($count since $main_branch):"
      echo "$branch_commits" | head -5
      [ "$count" -gt 5 ] && echo "  ... and $((count - 5)) more"
      echo ""
      echo "Recent on $main_branch:"
      git log --oneline -3 "$main_branch"
    else
      echo "Just branched from $main_branch. Recent commits:"
      git log --oneline -4
    fi
  else
    echo "Recent commits:"
    git log --oneline -5
  fi
fi

# Uncommitted changes
changed=$(git diff --name-only HEAD 2>/dev/null)
if [ -n "$changed" ]; then
  echo ""
  echo "Uncommitted changes:"
  echo "$changed"
fi

echo "=== End Git Context ==="
