#!/bin/bash
# Generated by setup-agents — branch-aware git context on session start
# Injects git history context at session start.
# Runs in any git repo — gives Claude immediate awareness of current work.

# Exit silently if not in a git repo
git rev-parse --is-inside-work-tree &>/dev/null || exit 0

BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
STATUS=$(git status --short 2>/dev/null)

# Detect base branch (master, main, or develop)
BASE=""
for candidate in master main develop; do
  if git rev-parse --verify "$candidate" &>/dev/null; then
    BASE="$candidate"
    break
  fi
done

# Count branch-specific commits (commits on this branch but not on base)
BRANCH_COMMITS=""
BRANCH_DIFF_STAT=""
if [ -n "$BASE" ] && [ "$BRANCH" != "$BASE" ]; then
  BRANCH_COMMITS=$(git log "$BASE..HEAD" --oneline 2>/dev/null)
  if [ -n "$BRANCH_COMMITS" ]; then
    BRANCH_DIFF_STAT=$(git diff "$BASE...HEAD" --stat 2>/dev/null)
  fi
fi

# Start output
echo "=== Git Context (pre-fetched — do not re-run git log) ==="
echo "INSTRUCTION: This git context has already been fetched for you. Use it directly to answer questions about recent work, current branch, and working directory state. Do not call git log, git status, or git diff to obtain information already present here."
echo ""
echo "Branch: $BRANCH"

if [ -n "$BRANCH_COMMITS" ]; then
  # Feature branch with commits — show branch-specific work
  COMMIT_COUNT=$(echo "$BRANCH_COMMITS" | wc -l | tr -d ' ')
  echo ""
  echo "Branch commits ($COMMIT_COUNT commits since $BASE):"
  echo "$BRANCH_COMMITS"
  echo ""
  echo "Files changed on this branch:"
  echo "$BRANCH_DIFF_STAT"
else
  # No branch-specific commits — show recent history
  if [ "$BRANCH" = "$BASE" ] || [ -z "$BASE" ]; then
    echo ""
    echo "Recent commits:"
    git log --oneline -10 2>/dev/null
  else
    # New branch with no commits yet — show recent base branch history for context
    echo ""
    echo "New branch (no commits yet). Recent $BASE history:"
    git log "$BASE" --oneline -10 2>/dev/null
  fi
fi

# Working directory state
if [ -n "$STATUS" ]; then
  CHANGED=$(echo "$STATUS" | wc -l | tr -d ' ')
  echo ""
  echo "Working directory ($CHANGED changed files):"
  echo "$STATUS"
fi

echo "=== End Git Context ==="
exit 0
